general:
  package: 'netdata'
  name: 'netdata'
  version: '1.1.0-1'
  depends: []
  conflicts: []
  developer: 'Costa Tsaousis'
  email: 'fboudra+adm@gmail.com'
  website: 'https://github.com/firehol/netdata'
  architecture: 'x86-64'
  firmware: '2.5.0'
  maintainer: 'Fathi Boudra'
  model:
  - '50xx'
  - '51xx'
adm-desktop:
  app:
    type: 'custom'
    protocol: 'http'
    port: 19999
    url: '/'
  privilege:
    accessible: 'users'
    customizable: true
register:
  prerequisites:
    enable-service: []
    restart-service: []
  boot-priority:
    start-order: 20
    stop-order: 80
  port: [19999]
